# Generated by Django 3.2 on 2021-04-17 07:29

import apps.account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_myuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='website',
            field=models.CharField(blank=True, max_length=150, validators=[apps.account.validators.validate_website_url], verbose_name='Website'),
        ),
    ]
