# Generated by Django 3.2 on 2021-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_myuser_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='otp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='otp_create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
