# Generated by Django 3.2 on 2021-04-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210417_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneModel',
        ),
    ]
