# Generated by Django 3.2 on 2021-04-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_phonemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, default='profile_photo/default_profile.png', null=True, upload_to='profile_photo', verbose_name='Image'),
        ),
    ]
