# Generated by Django 3.2 on 2021-04-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_myuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, max_length=100, verbose_name='Bio'),
        ),
    ]
