# Generated by Django 3.2 on 2021-04-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_following'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Following',
            new_name='UserFollowing',
        ),
    ]
